name = input("PLEASE Enter your name to continue...")
age = input("PLEASE Enter your age to continue...")
print(f"Hello {name}, you are {age} years old.")
city = input("PLEASE Enter your city to continue...")
print(f"Hello {name}, you are {age} years old and you live in {city}.")
print("Thank you for providing your information!")
email = input("enter your email...")
